### PR TITLE
Use only one build dir

### PR DESCRIPTION
**Pull request by wiiaboo**
Only tested this with my usecase (64-bit only).
Will test with 32-bit as well tomorrow.

The separate "build_successful$bits" mean that in case something happens during 64-bit compilation the 32-bit won't get compiled again.

### CODE REVIEW

**Comment by jb-alvarado** [comment]
look very good! I will run a test tomorrow.

**Comment by jb-alvarado** [comment]
have you a idea how we can use this for the normal zipped sources to?

**Comment by wiiaboo** [comment]
Don't delete them with do_checkIfExist, delete them at the end of the
script and then change every zip source to use the existing dir instead of
downloading.

**Comment by jb-alvarado** [comment]
And maybe we need to check to, witch repos have distclean support instead of clean.

**Comment by jb-alvarado** [comment]
I think the "touch build_successful$bits" don't work right at the moment. By me it has run two times the same target.

**Comment by wiiaboo** [comment]
Yeah, I think it's because you need deletesource to be on. Just replace the
"else" before and switch to "fi"

**Comment by wiiaboo** [comment]
What do you think of https://github.com/jb-alvarado/media-autobuild_suite/commit/fa1d1f63f4ede5f185e516f6168f90291a2e7395 ?

**Pull request merged**
