### PR TITLE
bat: end session after writing profiles

### PR DESCRIPTION
**Pull request by schmidthubert**
see https://github.com/jb-alvarado/media-autobuild_suite/issues/876

### CODE REVIEW

**Comment by wiiaboo** [comment]
What does this do?

**Comment by schmidthubert** [comment]
Because exit isn't possible then there is a different way:
https://unix.stackexchange.com/questions/423958/what-is-the-purpose-of-bash-logout/424297

**Comment by wiiaboo** [comment]
Why do you expect this to work in a .bat file?

**Comment by schmidthubert** [comment]
It works for me for weeks now ...

**Comment by schmidthubert** [comment]
https://sourceforge.net/p/mingw/mailman/message/8685967/

**Comment by wiiaboo** [comment]
The issue this is fixing never existed for me, this will just not do anything since there's no such file and it's not a valid executable for Windows even if it did exist, because .bash_logout is a bash executable script.

So again, what is this fixing and how is it fixing it?

**Comment by schmidthubert** [comment]
I can't try right now. Have lots of things running/open, will try in 10min  ...

**Comment by schmidthubert** [comment]
Yours doesn't work, keeps my white window open. Hmm, will remove this PR now because you don't get that behavior at all, others all the time, some just now and then, and for some people something works and for others it does not. So I don't know anymore what's going on with msys ...

**Pull request closed without merging**
