### PR TITLE
Git check

### PR DESCRIPTION
**Pull request by wiiaboo**
Big fixes, so opening a pull request.

I'm adding checks for every package to prevent build fails not to fix, because apparently it works.

Will test as soon as I finish ricing every package.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Lol, can't test because waio's git is down.

**Comment by jb-alvarado** [comment]
Look fine for me, when you test has work we can push it.

**Comment by wiiaboo** [comment]
mpv still compiles without waio, so I should be able to test anyway.

**Comment by wiiaboo** [comment]
Test seems ok. Will merge.

**Pull request merged**
