### PR TITLE
Improved FFmpeg options

### PR DESCRIPTION
**Pull request by wiiaboo**
Should be fine to merge as is since it uses the same options by default, but since it will be a big change overall I'll keep this as a PR until I've made every lib optional and until I find a way to notify of the possibility of using your own `ffmpeg_options.txt` file.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Don't worry about the amount of tiny commits, I'll squash most onto a single one before merging.

**Comment by wiiaboo** [comment]
I know fontconfig and freetype can be included without libass, I just took them from the default because they get added automatically with --enable-libass.

In the example ffmpeg_config.txt that gets created I'll keep them so people know they can compile them individually. Still haven't decided how I'll do that.

**Comment by jb-alvarado** [comment]
Ah ok, that is nice! The changes a very nice and I think it will be very useful, it makes the build process much faster, when you only need ffmpeg with one or two libs.

**Comment by wiiaboo** [comment]
```
[compiler list]
msys2Arch=2
arch=1
free=1
ffmbc=1
vpx=2
x264=2
x265=2
soxB=2
ffmpegB=1
mp4box=2
mplayer=2
mpv=2
mkv=2
```
Worked

**Comment by jb-alvarado** [comment]
Can I edit the batch file, or destroy this your merge request?

**Comment by wiiaboo** [comment]
I'm trying with a few other different ways first.
And we still have to figure out how to let people know about this.

**Comment by jb-alvarado** [comment]
Ok. We can add a selecting point to the batch. 

I would like to change some little things, like 7za.exe and remove the opt folder.

**Comment by wiiaboo** [comment]
Sure, change what you want.
If people choose to use ffmpeg_options.txt you can create a file with:
```
--enable-librtmp --enable-gnutls --enable-frei0r --enable-libbluray --enable-libcaca --enable-libopenjpeg --enable-libass --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libsoxr --enable-libtwolame --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvo-aacenc --enable-libopus --enable-libvidstab --enable-libxavs --enable-libxvid
--enable-libzvbi --enable-libdcadec --enable-libbs2b --enable-decklink --enable-libutvideo --enable-libgme --enable-nonfree --enable-nvenc --enable-libfdk-aac
```
This is equivalent to $DEFAULT_FFMPEG_OPTS in the beginning of `media-suite_compile.sh`.
Also, maybe some way to open ffmpeg_options.txt after choosing for people to edit it before continuing with the rest of the .bat. Or just a `pause` saying "You can edit /build/ffmpeg_options.txt now" before moving on.

**Comment by jb-alvarado** [comment]
Yes a pause will be enough, and saving the something in the ini, that the pause comes not always.

**Comment by wiiaboo** [comment]
Wow, that last one with everything turned off except FFmpeg itself gives a really small ffmpeg.exe (6.5MB with packing, 15MB without).

With `--disable-sdl` added just 6.4MB. It's mostly so there's no ffplay.exe.

Now to finally test with everything default, without ffmpeg_options.

**Comment by wiiaboo** [comment]
Successfully built everything, finally.

**Comment by wiiaboo** [comment]
Doing one final test and will merge if all is ok.

**Pull request merged**
