### PR TITLE
Batch: Removed wget-pack.exe, replaced functions with powershell

### PR DESCRIPTION
**Pull request by 1480c1**
Replaced wget-pack.exe functions with powershell equivalent. https://github.com/jb-alvarado/media-autobuild_suite/pull/1041
It tested working for me.

### CODE REVIEW

**Comment by 1480c1** [comment]
I see, allowclober is not on 5, back to the drawing board. Though I can implement those, just a sec.

**Comment by schmidthubert** [comment]
Can you not just make your branch the master and delete everything else then? Sorry I'm not a git guru!

**Comment by 1480c1** [comment]
Sure!
btw, do `git clone <GIT URL> --branch <BRANCH> <DESTFOLDER>

**Comment by 1480c1** [comment]
Things to note so far:
- You can't remove NuGet Package provider (You would have to manually delete the things, it doesn't really affect anything)

**Comment by 1480c1** [comment]
Try to replace line 1180 with `echo.Install-PackageProvider -Name "NuGet" -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser -Confirm:$false`
the confirm:$False should act as an automatic yes

**Comment by schmidthubert** [comment]
OK, that I could have figured out by myself now having to use -Confirm:$false a lot in Exchange PS scripts now and then LOL  ;) BRB ...

**Comment by schmidthubert** [comment]
Still no dice, it's still asking the same silly question, argh!?

**Comment by 1480c1** [comment]
hmm

**Comment by 1480c1** [comment]
Try to replace line 1179 and 1180 with
``` batch
echo.if ^(!^(Get-Module -Name PackageManagement^)^) {
echo.Install-Module -Name PackageManagement -Scope CurrentUser -Force -confirm:$false
```

**Comment by 1480c1** [comment]
I'm still setting up my windows 7 vm (can't download sp1 because microsoft.com requires a newer version of ie, but I can't download a newer ie without accessing microsoft.com

**Comment by schmidthubert** [comment]
If I change line 1179+1180 like you said then the question changes back to the same long question as in my first reply here. Maybe I should upgrade to PS 6.1.2 ? But that wouldn't be the default PS install for Win7 anymore then ...

**Comment by schmidthubert** [comment]
As for your download problems use chrome or FF and install User-Agent faker Addon ... :+1:

**Comment by schmidthubert** [comment]
https://www.microsoft.com/en-US/download/details.aspx?id=5842

**Comment by 1480c1** [comment]
I think I have an idea, let me quickly code it and upload.

**Comment by 1480c1** [comment]
Okay, I just made it so that it will manually download the dll to the supposed correct place, based on your previous error and it should work. I think.

**Comment by schmidthubert** [comment]
What I said earlier that in Win10 nuget was installed isn't true, I cannot find it. Tried your news batch there as well now but there's nothing in the assemblies directory at all, and then it errors again with the pcsx allowclobber error. So you should prepare a Win10 VM as well with no PS v6 on it but just 5.1.

Anyway, must go for now and hit the sack, need to get up early. Don't forget to make snapshots if you're playing in a VM, TTYL ... :+1:

**Comment by 1480c1** [comment]
Good Night, still working on it.

**Comment by 1480c1** [comment]
Opps

**Comment by 1480c1** [comment]
So far, it works on a fresh windows 8.1 installation with no modifications.

**Comment by wiiaboo** [comment]
Mainstream support for Win 7 has ended in 2015 and security updates end next year, so as an end-user you shouldn't really be using it.
I'm fine with hard-requiring modern versions of Powershell, as long as you can update to them.

**Comment by 1480c1** [comment]
> Unfortunately for Win7 that is a ps1 in a zip and not an msu package and that ps1 cannot be run without changing the PS execution-policy first and will require admin permissions to install plus a reboot anyway

Actually, since its a package it contains microsoft's signature at the bottom
``` powershell
    # SIG # Begin signature block
    $ MIIDLwYJKoZIhvcNAQcCoII.....
```
so it doesn't need executionpolicy bypass. It will require a restart though.

**Comment by 1480c1** [comment]
Actually, I lied.

**Comment by schmidthubert** [comment]
Yes, default is all undefined, I checked. I used unrestricted and that worked then.

**Pull request merged**
