### PR TITLE
Fix GnuTLS compilation since MinGW updated Nettle.

### PR DESCRIPTION
**Pull request by wiiaboo**
Also fix problems with LF endings in the .bat file.
And add "noDepth" to luajit.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Ok, just left the fixes and will do a separate pull request for the single build directory.

**Comment by jb-alvarado** [comment]
In the msys2 mailing list they have write that the gnutls 3.4.0 version works with nettle 3.1-1 to, so maybe we don't need to build nettle by our self.

**Comment by wiiaboo** [comment]
I tried that version. The build failed for some reason.

**Comment by jb-alvarado** [comment]
Maybe we need to install mingw-w64-x86_64-libidn 1.30-1. This they also write in the list.

**Comment by wiiaboo** [comment]
MinGW's nettle seems to be missing hogweed so we can't use it yet.

**Comment by jb-alvarado** [comment]
gnutls 3.4.0 works with nettle 3.1. but it has a error in time.h. Maybe we can fix that and use the nettle from pacman again. Here the Config what we need for it:
 `./configure --build=$targetBuild --host=$targetHost --prefix=$LOCALDESTDIR --bindir=$LOCALDESTDIR/bin-global --disable-guile --enable-cxx --disable-doc --disable-tests --disable-shared --with-zlib --without-p11-kit --disable-rpath --disable-gtk-doc --disable-libdane --enable-local-libopts HOGWEED_CFLAGS=-I$MINGW_PREFIX/include HOGWEED_LIBS=-L$MINGW_PREFIX/lib`

**Comment by wiiaboo** [comment]
Probably mingw's sed patch in their PKGBUILD

**Comment by jb-alvarado** [comment]
This config line works better, but it don't find autoopts, strange because it is in the sources from gnutls...

`CFLAGS+=" -D_POSIX_C_SOURCE src/libopts" CXXFLAGS+=" -D_POSIX_C_SOURCE src/libopts" ./configure --build=$targetBuild --host=$targetHost --prefix=$LOCALDESTDIR --bindir=$LOCALDESTDIR/bin-global --disable-guile --enable-cxx --disable-doc --disable-tests --disable-shared --with-zlib --without-p11-kit --disable-rpath --disable-gtk-doc --disable-libdane --with-libregex-libs=-lsystre --enable-local-libopts HOGWEED_CFLAGS=-I$MINGW_PREFIX/include HOGWEED_LIBS=-L$MINGW_PREFIX/lib`

**Comment by wiiaboo** [comment]
Btw, what is gnurx needed for'

**Comment by jb-alvarado** [comment]
I think it was for file.

**Pull request merged**
