### PR TITLE
Batch: Condense getmingws into one with Pacboy

### PR DESCRIPTION
**Pull request by 1480c1**
We can either use pacboy or just replace the x and i with x86_64 and i386.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Sure, does pactoys-git come o.o.b. with msys?

**Comment by 1480c1** [comment]
I think so, I have gotten travis to work with it multiple times with a new vm. It's also included in base and base-devel.

**Comment by schmidthubert** [comment]
if [%try%]==[y] (mujs

???

**Comment by 1480c1** [comment]
hmm, I don't know where that came from.

**Pull request merged**
