### PR TITLE
Build gpac and mp4box shared

### PR DESCRIPTION
**Pull request by wiiaboo**
We'll wait for gpac to reply before commiting this.

### CODE REVIEW

**Comment by jb-alvarado** [comment]
Have post here: https://github.com/gpac/gpac/issues/139

**Comment by wiiaboo** [comment]
By the way, if you noticed, static mp4box also disables a52dec and libmad, so we could probably remove those.

**Comment by jb-alvarado** [comment]
Hm, when this is only for gpac than yes we can remove them. But maybe they was for sox to. I don't remember exactly.

**Comment by jb-alvarado** [comment]
It looks like, that it takes a bit long for a fix. So what you think we merge your fix?

**Comment by wiiaboo** [comment]
What do you think is better? Shared or checkout to commit before and continue building static?

**Comment by jb-alvarado** [comment]
I think we can build for now the shared and when it is fixed, we can change again. Ok?

**Pull request merged**
