### PR TITLE
Remove redundant extra-libs from ffmpeg

### PR DESCRIPTION
**Pull request by wiiaboo**
FFmbc can be left as is since it's based on an old version of FFmpeg, so things might or not break if we take extra-libs off, but I just finished a full compilation from scratch and there were no problems.

How about on your side, @jb-alvarado ?

### CODE REVIEW

**Comment by jb-alvarado** [comment]
I just finish the 32bit compiling, and yes ffmpeg build without the extra-libs. I only had to fix libsndfile:

```
if [[ ! -f ./configure ]]; then
		sed -i "s/python/python2/" autogen.sh
        ./autogen.sh
    else
```

**Comment by wiiaboo** [comment]
Oh? Even with https://github.com/jb-alvarado/media-autobuild_suite/commit/84dfc8a2a8099faa1aa6ad07b5b35950d62b060d ?
I was compiling again from zero after https://github.com/jb-alvarado/media-autobuild_suite/commit/f2877b19defce205c9b1ffa69126eb2272f2b0da and twolame failed because ffmpeg doesn't use pkg-config.

**Comment by jb-alvarado** [comment]
Ah... This I have not see. I only get the shell script from you...

**Comment by wiiaboo** [comment]
32-bit bit from scratch worked.

**Comment by jb-alvarado** [comment]
ffmpeg 64bit without extra-libs runs here also smooth.

**Comment by wiiaboo** [comment]
64-bit build from scratched worked too. I think it's safe to merge.

**Pull request merged**
