### PR TITLE
enable liblensfun for full ffmpeg

### PR DESCRIPTION
**Pull request by LigH-de**
Add liblensfun to set of libraries enabled in full ffmpeg build

### CODE REVIEW

**Comment by wiiaboo** [comment]
Why do you want to add a broken lib to the default options?

**Comment by LigH-de** [comment]
I did not know it is "broken"; you declared it as "untested", so I wanted to test it.

Postpone it or remove it, you know much more than me.

**Comment by wiiaboo** [comment]
Did you not open this issue? https://github.com/jb-alvarado/media-autobuild_suite/issues/899
What about that invites you to give me more people complaining about their build being broken?

**Comment by LigH-de** [comment]
I look at your project site. I see "Add lensfun (untested)" in your commit descriptions. That makes me curious, I want to test it. Now you tell me here that I am not supposed to test it. So what do you expect me to do in this case? I thought it could be a small mistake, you just forgot a little detail, possibly easy to fix. No, I guessed wrong, sorry. But your reaction discourages me from trying and telling you about issues I found. Do you prefer mistakes to remain, because noone wants to find them? I don't get it.

**Comment by wiiaboo** [comment]
> I look at your project site. I see "Add lensfun (untested)" in your commit descriptions. That makes me curious, I want to test it. Now you tell me here that I am not supposed to test it. 

You can test it all you want. You can even fix it and PR the fix. That's why there's code in the suite to compile it if it's enabled.

> So what do you expect me to do in this case? I thought it could be a small mistake, you just forgot a little detail, possibly easy to fix. No, I guessed wrong, sorry. But your reaction discourages me from trying and telling you about issues I found.

I added lensfun because someone asked for it, but I don't have any time to spend on fixing it. I've neither tested it myself nor compiled with FFmpeg so I don't want to add it to the fucking huge list of libs that everyone picks and then comes complaining about.

> Do you prefer mistakes to remain, because noone wants to find them? I don't get it.

I'd prefer someone else taking this over, since I've lost interest in working on it and haven't even used it myself for months. I'd prefer the people that ask for obscure libs to get fixes for themselves or complain to the upstream developers about it.

**Comment by wiiaboo** [comment]
The full build option of FFmpeg options is meant to show libs that you CAN compile with FFmpeg with the suite, not that you SHOULD use.

**Comment by hydra3333** [comment]
Thank you for your wonderful work.

**Pull request closed without merging**
