### PR TITLE
*.sh & Batch: Convert all indentions to spaces

### PR DESCRIPTION
**Pull request by 1480c1**
Convert all 4 spaces at the beginning of the files to tab indentions. Probably not necessary, but vscode likes to do this on its own.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Your commit message says the explicit opposite of what you're doing.

Is there any specific reason other than preference for converting **to** tabs? I much prefer spaces.

**Comment by 1480c1** [comment]
Not particularly, I'm fine with spaces. The commit message part probably came from because I wanted to quickly commit it before my laptop died.

**Comment by wiiaboo** [comment]
It could be argued that tabs are better for people that want variable length of indentation, but I also like aligning things by scope/parenthesis and for that to work you'd need to mix tabs and spaces.
It's mostly subjective anyway.

**Comment by 1480c1** [comment]
I see, I personally prefer tabs mainly because if I want to do a small edit on something, I usually use nano or vim as I'm usually already in a console and I don't want to open up explorer just to navigate to it to open up notepad++, and when using nano, I don't like having to hold right for every space due to the text being indented multiple times.

**Comment by schmidthubert** [comment]
https://gist.github.com/eevee/6721177

**Pull request closed without merging**
