### PR TITLE
Batch: Error if powershell version is less than 4

### PR DESCRIPTION
**Pull request by 1480c1**
Added preliminary check if powershell version if less than 4.

### CODE REVIEW

**Comment by 1480c1** [comment]
Hmm, let me move the logic over from batch to powershell.

**Comment by 1480c1** [comment]
That should fix it. I'm not exactly sure why it wasn't working before.

**Comment by schmidthubert** [comment]
Yes, that works, I tried with 6 instead of 4 which returned false, which is true  :smile:

**Comment by 1480c1** [comment]
Added a different link that has information on how to install it along with links to the required packages instead.

**Pull request merged**
